FROM fedora:35
RUN yum -y install redhat-lsb-core git subversion \
    desktop-file-utils wget nano rpm-build \
    qt5-qtbase-devel qt5-qtwebkit-devel qt5-linguist \
    qt5-qttools-devel qt5-qtbase-private-devel zlib-devel libXext-devel
