FROM ubuntu:21.04
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y --no-install-recommends install tzdata keyboard-configuration && \
    apt-get -y --no-install-recommends install sudo subversion git \
    && apt clean && rm -rf /var/lib/apt/lists/*
