FROM ubuntu:16.04
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y --no-install-recommends install tzdata keyboard-configuration && \
    apt-get -y --no-install-recommends install sudo subversion ca-certificates less lsb-release software-properties-common && \
    add-apt-repository -y ppa:git-core/ppa && apt-get -y update && \
    apt-get -y install git wget nano && \
    apt-get -y --no-install-recommends install \
    zlib1g-dev fakeroot build-essential devscripts debhelper g++ \
    libxcb-xinerama0 libgl1-mesa-dev && \
    add-apt-repository -y ppa:beineri/opt-qt-5.15.2-xenial && apt-get -y update && \
    apt-get -y install qt515* && \
    apt-get -y remove qt515doc && \
    apt clean && rm -rf /var/lib/apt/lists/*
