FROM ubuntu:16.04
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get -y --allow-insecure-repositories update && \
    apt-get -y --allow-unauthenticated --no-install-recommends \
    install tzdata keyboard-configuration && \
    apt-get -y --allow-unauthenticated --no-install-recommends \
    install sudo subversion ca-certificates less lsb-release &&
    add-apt-repository -y ppa:git-core/ppa && apt-get update && apt-get install -y git &&
    apt-get -y --allow-unauthenticated --no-install-recommends \
    zlib1g-dev fakeroot build-essential devscripts debhelper g++ \
    libqt4-dev libqtwebkit-dev \
    && apt clean && rm -rf /var/lib/apt/lists/*
