FROM bilelmoussaoui/flatpak-github-actions:kde-5.15
RUN flatpak uninstall -y --noninteractive org.kde.Platform/x86_64/5.15 org.kde.Sdk/x86_64/5.15
RUN flatpak install -y --noninteractive flathub org.kde.Platform/x86_64/5.12 org.kde.Sdk/x86_64/5.12 io.qt.qtwebkit.BaseApp/x86_64/5.12
