name: Build Images

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: 'test', tag: 'test', repo: 'wachii/ubuntu-qt', qt: 5 }
          - { name: 'hirsute', tag: '21.04', repo: 'wachii/ubuntu-qt', qt: 5 }
          - { name: 'debian-10.9', tag: '10.9', repo: 'wachii/debian-qt', qt: 5 }

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Create image ${{ matrix.config.tag }}
        run:  docker buildx build -t ${{ matrix.config.repo }}:${{ matrix.config.tag }} - < Dockerfile-${{ matrix.config.name }}
        
      - name: Login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERPASS }}
        
      - name: Push image
        run: docker push ${{ matrix.config.repo }}:${{ matrix.config.tag }} 
  
