name: Build Images

on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          #- { name: 'test', tag: 'test', repo: 'wachii/ubuntu-qt' }
          #- { name: 'ubuntu-21.04', tag: '21.04', repo: 'wachii/ubuntu-qt' }
          #- { name: 'ubuntu-16.04', tag: '16.04', repo: 'wachii/ubuntu-qt' }
          #- { name: 'ubuntu-16.04-qt5', tag: '16.04', repo: 'wachii/ubuntu-qt5' }
          #- { name: 'xenial-qt512', tag: '5.12', repo: 'wachii/xenial-qt' }
          #- { name: 'xenial-qt515', tag: '5.15.2', repo: 'wachii/xenial-qt' }
          #- { name: 'xenial-qt514', tag: '5.14.0', repo: 'wachii/xenial-qt' }
          #- { name: 'debian-10.9', tag: '10.9', repo: 'wachii/debian-qt' }
          #- { name: 'debian-11.7', tag: '11.7', repo: 'wachii/debian-qt' }
          #- { name: 'fedora-35', tag: '35', repo: 'wachii/fedora-qt }
          #- { name: 'fedora-34', tag: '34', repo: 'wachii/fedora-qt' }
          #- { name: 'opensuse-15.3', tag: '15.3', repo: 'wachii/opensuse-qt' }
          #- { name: 'archlinux', tag: 'devel', repo: 'wachii/archlinux' }
          #- { name: 'flatpak-5.12', tag: '5.12', repo: 'wachii/flatpak-kde' }
          #- { name: 'fedora-flatpak-base', tag: 'base', repo: 'wachii/fedora-flatpak' }
          #- { name: 'fedora-flatpak-kde5.12', tag: '5.12', repo: 'wachii/fedora-flatpak-kde' }
          #- { name: 'fedora-flatpak-kde5.15', tag: '5.15', repo: 'wachii/fedora-flatpak-kde' }
          #- { name: 'ubuntu-18.04-x86', tag: '18.04', repo: 'wachii/ubuntu-i386-qt' }
          - { name: 'ubuntu-18.04', tag: '18.04', repo: 'wachii/ubuntu-qt' }

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Create image ${{ matrix.config.name }}
        run:  docker buildx build -t ${{ matrix.config.repo }}:${{ matrix.config.tag }} -f Dockerfile-${{ matrix.config.name }} .
        
      - name: Login
        run: docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERPASS }}
        
      - name: Push image
        run: docker push ${{ matrix.config.repo }}:${{ matrix.config.tag }} 
  
