name: Create image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create image
        run: |
            docker buildx build -t wachii/ubuntu-qt:test - < Dockerfile-test
            docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERPASS }}
            docker push wachii/ubuntu-qt:test
